### ISSUE TITLE
Question - Drawing stuff after shaders are applied?

### ISSUE THREAD

**Issue by jon914** [HaxePunk/post-process#2]
Is there a way to "draw" stuff after the post-processing phase is over?

For example, if my game has an HUD layer (for a health bar, score, etc.), I'd like the shaders to do their work but _not_ apply to those elements.

From what I understand, it's not as simple as adding something to the display tree after the PostProcess view - that would pick up what's drawn in the next frame, I imagine.

**Comment by MattTuttle** [comment]
You could add a Sprite after the PostProcess layer and draw to that. Unfortunately there isn't a nice way to render with HaxePunk on another Sprite.

**Comment by jon914** [comment]
Thanks, adding a Sprite after the PostProcess layer did the trick.
